# Generated by Django 3.0.1 on 2019-12-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('btitle', models.CharField(max_length=255)),
                ('bauthor', models.CharField(blank=True, max_length=1023, null=True)),
                ('bedition', models.CharField(blank=True, max_length=1023, null=True)),
                ('bformat', models.CharField(blank=True, max_length=127, null=True)),
                ('bpages', models.IntegerField(blank=True, null=True)),
                ('brating', models.FloatField(blank=True, null=True)),
                ('bratcount', models.IntegerField(blank=True, null=True)),
                ('brevcount', models.IntegerField(blank=True, null=True)),
                ('bgenres', models.CharField(blank=True, max_length=1023, null=True)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bsname', models.CharField(blank=True, max_length=255, null=True)),
                ('bstel', models.CharField(max_length=8)),
                ('baddr', models.CharField(blank=True, max_length=255, null=True)),
                ('bosstel', models.CharField(blank=True, max_length=13, null=True)),
                ('bosspasswd', models.CharField(blank=True, max_length=255, null=True)),
                ('staffpasswd', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bookstore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cname', models.CharField(blank=True, max_length=255, null=True)),
                ('ctel', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('last_active_time', models.DateTimeField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('order_amount', models.FloatField()),
                ('order_type', models.IntegerField()),
                ('order_closetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseorder',
            fields=[
                ('poid', models.AutoField(primary_key=True, serialize=False)),
                ('porder_time', models.DateTimeField()),
                ('porder_amount', models.FloatField()),
                ('porder_type', models.IntegerField()),
                ('porder_closetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchaseorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('outprice', models.FloatField()),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockNotsale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.IntegerField()),
                ('outprice', models.FloatField()),
            ],
            options={
                'db_table': 'stock_notsale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=255, null=True)),
                ('stel', models.CharField(max_length=8)),
                ('scity', models.CharField(blank=True, max_length=31, null=True)),
                ('sregtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderdetail',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookstore.Order')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'orderdetail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchaseorderdetail',
            fields=[
                ('porder', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bookstore.Purchaseorder')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'purchaseorderdetail',
                'managed': False,
            },
        ),
    ]
