# Generated by Django 3.0.1 on 2020-01-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookstore.Book'),
        ),
    ]
